CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "BaumArt" (
    "BaumArtID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Art" character varying(255) NOT NULL,
    CONSTRAINT "PK_BaumArt" PRIMARY KEY ("BaumArtID")
);

CREATE TABLE "BaumMerkmal" (
    "BaumMerkmalID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Merkmal" character varying(255) NOT NULL,
    CONSTRAINT "PK_BaumMerkmal" PRIMARY KEY ("BaumMerkmalID")
);

CREATE TABLE "BaumZustand" (
    "BaumZustandID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Zustand" character varying(255) NOT NULL,
    CONSTRAINT "PK_BaumZustand" PRIMARY KEY ("BaumZustandID")
);

CREATE TABLE "Feldmitarbeiter" (
    "FeldmitarbeiterID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Vorname" character varying(150) NOT NULL,
    "Profilbild" bytea NULL,
    "ArbeitetNochInDerFirma" boolean NOT NULL,
    "Login" text NOT NULL,
    CONSTRAINT "PK_Feldmitarbeiter" PRIMARY KEY ("FeldmitarbeiterID")
);

CREATE TABLE "User" (
    "Loginname" text NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "IstAdminBerechtigt" boolean NOT NULL,
    "RefreshToken" text NOT NULL,
    "TokenErstelltAm" timestamp with time zone NOT NULL,
    "TokenLaeuftAbAm" timestamp with time zone NOT NULL,
    "IstUserAktiv" boolean NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Loginname")
);

CREATE TABLE "Waldeigentuemer" (
    "WaldeigentuemerID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Vorname" character varying(150) NOT NULL,
    "PLZ" integer NOT NULL,
    "Ort" character varying(200) NOT NULL,
    "MobileNr" text NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_Waldeigentuemer" PRIMARY KEY ("WaldeigentuemerID")
);

CREATE TABLE "Baum" (
    "BaumID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ParzellenNr" integer NOT NULL,
    "Name" character varying(255) NULL,
    "ErsteErfassung" timestamp with time zone NOT NULL,
    "LetzteBearbeitung" timestamp with time zone NOT NULL,
    "Baumhoehe" double precision NOT NULL,
    "Umfang" double precision NOT NULL,
    "Alter" integer NULL,
    "ArtID" integer NULL,
    "Bemerkung" text NULL,
    "WGS84_XKoordinaten" double precision NOT NULL,
    "WGS84_YKoordinaten" double precision NOT NULL,
    "EllipsoidischeHoehe" double precision NULL,
    "HoeheMeterUeberMeer" double precision NULL,
    "LV95_EKoordinaten" double precision NOT NULL,
    "LV95_NKoordinaten" double precision NOT NULL,
    "FeldmitarbeiterID" integer NULL,
    "WaldeigentuemerID" integer NULL,
    CONSTRAINT "PK_Baum" PRIMARY KEY ("BaumID"),
    CONSTRAINT "FK_Baum_BaumArt_ArtID" FOREIGN KEY ("ArtID") REFERENCES "BaumArt" ("BaumArtID"),
    CONSTRAINT "FK_Baum_Feldmitarbeiter_FeldmitarbeiterID" FOREIGN KEY ("FeldmitarbeiterID") REFERENCES "Feldmitarbeiter" ("FeldmitarbeiterID"),
    CONSTRAINT "FK_Baum_Waldeigentuemer_WaldeigentuemerID" FOREIGN KEY ("WaldeigentuemerID") REFERENCES "Waldeigentuemer" ("WaldeigentuemerID")
);

CREATE TABLE "BaumMerkmalRelation" (
    "BaumID" integer NOT NULL,
    "MerkmalID" integer NOT NULL,
    CONSTRAINT "PK_BaumMerkmalRelation" PRIMARY KEY ("MerkmalID", "BaumID"),
    CONSTRAINT "FK_BaumMerkmalRelation_BaumMerkmal_MerkmalID" FOREIGN KEY ("MerkmalID") REFERENCES "BaumMerkmal" ("BaumMerkmalID") ON DELETE CASCADE,
    CONSTRAINT "FK_BaumMerkmalRelation_Baum_BaumID" FOREIGN KEY ("BaumID") REFERENCES "Baum" ("BaumID") ON DELETE CASCADE
);

CREATE TABLE "BaumZustandRelation" (
    "BaumID" integer NOT NULL,
    "ZustandID" integer NOT NULL,
    CONSTRAINT "PK_BaumZustandRelation" PRIMARY KEY ("ZustandID", "BaumID"),
    CONSTRAINT "FK_BaumZustandRelation_BaumZustand_ZustandID" FOREIGN KEY ("ZustandID") REFERENCES "BaumZustand" ("BaumZustandID") ON DELETE CASCADE,
    CONSTRAINT "FK_BaumZustandRelation_Baum_BaumID" FOREIGN KEY ("BaumID") REFERENCES "Baum" ("BaumID") ON DELETE CASCADE
);

CREATE TABLE "Foto" (
    "FotoID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Fotobytes" bytea NOT NULL,
    "BaumID" integer NOT NULL,
    CONSTRAINT "PK_Foto" PRIMARY KEY ("FotoID"),
    CONSTRAINT "FK_Foto_Baum_BaumID" FOREIGN KEY ("BaumID") REFERENCES "Baum" ("BaumID") ON DELETE CASCADE
);

INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (1, 'Abies alba');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (2, 'Acer campestris');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (3, 'Acer opalus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (4, 'Acer platanoides');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (5, 'Acer pseudoplatanus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (6, 'Alnus glutinosa');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (7, 'Alnus incana');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (8, 'Betula pendula');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (9, 'Betula pubescens');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (10, 'Carpinus betulus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (11, 'Castanea sativa');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (12, 'Cornus mas');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (13, 'Corylus avellana');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (14, 'Crataegus laevigata');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (15, 'Crataegus monogyna');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (16, 'Fagus sylvatica');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (17, 'Frangula alnus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (18, 'Fraxinus excelsior');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (19, 'Fraxinus ornus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (20, 'Ilex aquifolium');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (21, 'Juglans regia');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (22, 'Juniperus communis');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (23, 'Laburnum alpinum');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (24, 'Laburnum anagyroides');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (25, 'Larix decidua');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (26, 'Malus sylvestris');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (27, 'Ostrya carpinifolia');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (28, 'Picea abies');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (29, 'Pinus cembra');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (30, 'Pinus mugo ssp.uncinata');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (31, 'Pinus sylvestris');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (32, 'Populus alba');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (33, 'Populus nigra');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (34, 'Populus tremula');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (35, 'Prunus avium');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (36, 'Prunus padus');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (37, 'Prunus spinosa');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (38, 'Pyrus pyraster');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (39, 'Quercus petraea');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (40, 'Quercus pubescens');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (41, 'Quercus robur');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (42, 'Salix alba');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (43, 'Salix caprea');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (44, 'Sambucus nigra');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (45, 'Sorbus aria');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (46, 'Sorbus aucuparia');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (47, 'Sorbus domestica');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (48, 'Sorbus torminalis');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (49, 'Taxus baccata');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (50, 'Tilia cordata');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (51, 'Tilia platyphyllos');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (52, 'Ulmus glabra');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (53, 'Ulmus laevis');
INSERT INTO "BaumArt" ("BaumArtID", "Art")
VALUES (54, 'Ulmus minor');

INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (1, 'Keine Strukturen ');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (2, 'mehrstämmig tiefer 1 m');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (3, 'Zwiesel untere Stammhälfte');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (4, 'Flötenbaum');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (5, 'Spechthöhle gross');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (6, 'kleine Spechthöhle/n');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (7, 'Höhle/n in Totholz');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (8, 'Frasshöhle in Totholz');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (9, 'Mulmhöhle');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (10, 'hohler Stammfuss');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (11, 'andere Höhle/Vertiefung');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (12, 'wassergefüllte Höhle (Dendrotelm)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (13, 'Riss/Rindenverletzung < 50 cm');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (14, 'Riss/Rindenverletzung > 50 cm');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (15, 'Riss/Rindenverletzung verheilt');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (16, 'Astausbruch gross');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (17, 'Kronenbruch');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (18, 'Stammbruch');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (19, 'Totholz in der Krone (> 10 cm)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (20, 'Hexenbesen');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (21, 'Klebäste');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (22, 'Wucherung (Maserknolle/Krebs)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (23, 'Baumpilze verholzt');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (24, 'Baumpilze weich');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (25, 'Moose  (> 10 % Stammfläche)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (26, 'Flechten (> 10 % Stammfläche)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (27, 'Efeu');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (28, 'Waldrebe');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (29, 'Farne');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (30, 'Misteln');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (31, 'Epiphyten (weitere)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (32, 'Harz-/Saftfluss');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (33, 'Ameisenstrasse');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (34, 'Frassgänge von Insekten');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (35, 'Bienen-/Wespen-/Hornissennest');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (36, 'Horst (> 30 cm)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (37, 'Nest (< 30 cm)');
INSERT INTO "BaumMerkmal" ("BaumMerkmalID", "Merkmal")
VALUES (38, 'Säugetierhöhle Stammfuss');

INSERT INTO "BaumZustand" ("BaumZustandID", "Zustand")
VALUES (1, 'tot');
INSERT INTO "BaumZustand" ("BaumZustandID", "Zustand")
VALUES (2, 'lebendig');
INSERT INTO "BaumZustand" ("BaumZustandID", "Zustand")
VALUES (3, 'stehend');
INSERT INTO "BaumZustand" ("BaumZustandID", "Zustand")
VALUES (4, 'liegend');

CREATE INDEX "IX_Baum_ArtID" ON "Baum" ("ArtID");

CREATE INDEX "IX_Baum_FeldmitarbeiterID" ON "Baum" ("FeldmitarbeiterID");

CREATE INDEX "IX_Baum_WaldeigentuemerID" ON "Baum" ("WaldeigentuemerID");

CREATE INDEX "IX_BaumMerkmalRelation_BaumID" ON "BaumMerkmalRelation" ("BaumID");

CREATE INDEX "IX_BaumZustandRelation_BaumID" ON "BaumZustandRelation" ("BaumID");

CREATE INDEX "IX_Foto_BaumID" ON "Foto" ("BaumID");

SELECT setval(
    pg_get_serial_sequence('"BaumArt"', 'BaumArtID'),
    GREATEST(
        (SELECT MAX("BaumArtID") FROM "BaumArt") + 1,
        nextval(pg_get_serial_sequence('"BaumArt"', 'BaumArtID'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"BaumMerkmal"', 'BaumMerkmalID'),
    GREATEST(
        (SELECT MAX("BaumMerkmalID") FROM "BaumMerkmal") + 1,
        nextval(pg_get_serial_sequence('"BaumMerkmal"', 'BaumMerkmalID'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"BaumZustand"', 'BaumZustandID'),
    GREATEST(
        (SELECT MAX("BaumZustandID") FROM "BaumZustand") + 1,
        nextval(pg_get_serial_sequence('"BaumZustand"', 'BaumZustandID'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230131212408_CreateDatabase', '7.0.1');

COMMIT;

